version: 2
updates:
  # Manifest of Skillz app
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "automated pr"
      - "skillz-app"
    groups:
      app-packages:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Manifest of Skillz slack bot
  - package-ecosystem: "npm"
    directory: "bot-slack/"
    target-branch: "main"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "automated pr"
      - "skillz-bot"
    groups:
      bot-packages:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
