INSERT INTO "public"."Tag" ("name") VALUES
('3D'),
('agile'),
('AGILE'),
('ai'),
('AI/ML'),
('analytics'),
('angular'),
('ansible'),
('api'),
('appliance'),
('architecture'),
('artifacts'),
('auditing'),
('availability'),
('aws'),
('backend'),
('BDD'),
('behavior'),
('bi'),
('blockchain'),
('bpmn'),
('business'),
('caas'),
('change management'),
('ci/cd'),
('CI/CD'),
('Client: Decathlon'),
('cloud'),
('cms'),
('coaching'),
('coaching individuel'),
('conduite du changement'),
('confidentiality'),
('consulting'),
('containers'),
('continous improvement'),
('continuous improvement'),
('craftsmanship'),
('crisismanagement'),
('data'),
('database'),
('Data Engineering Pipelines'),
('Datascience'),
('delivery'),
('design'),
('design system'),
('Design Thinking'),
('desktop'),
('devops'),
('docker'),
('documentation'),
('Eco-Conception'),
('Eco-Ingénierie'),
('elastic'),
('ergonomie'),
('execution'),
('facilitation'),
(',fgg'),
('field'),
('Figma'),
('FLUX'),
('framework'),
('frontend'),
('gaming'),
('gcp'),
('GCP Cloud Architect'),
('Generative AI'),
('gestion de risques'),
('Gitlab'),
('Google Cloud Infra'),
('gouvernance'),
('governance'),
('graph'),
('greenit'),
('hardening'),
('hardware'),
('IA'),
('IAAS'),
('IAC'),
('ias'),
('ide'),
('identity'),
('influence'),
('integrity'),
('iot'),
('java'),
('javascript'),
('JAVASCRIPT'),
('kafka'),
('kubernetes'),
('language'),
('Language'),
('lean'),
('library'),
('low-code'),
('LOW LEVEL'),
('Machine Learning'),
('management'),
('Microfront end'),
('Microservice'),
('middleware'),
('ml'),
('mobile'),
('Mobile'),
('modeling'),
('monitoring'),
('MUI'),
('Native'),
('network'),
('nocode'),
('nosql'),
('observability'),
('opensource'),
('operations'),
('ops'),
('organisation'),
('organization'),
('os'),
('paas'),
('paradigm'),
('performance'),
('php'),
('platform'),
('poo'),
('product'),
('programming'),
('prototyping'),
('PYSPARK'),
('python'),
('Python'),
('qa'),
('React'),
('reactive programming'),
('recruitment'),
('Redux'),
('relations'),
('Remotion'),
('repository'),
('research'),
('saas'),
('sales'),
('scala'),
(' script'),
('script'),
('search'),
('security'),
('sre'),
('strategy'),
('strength'),
('Tanstack React Query'),
('testing'),
('tooling'),
('transformation'),
('typescript'),
('ux'),
('ux design'),
('version control'),
('virtualization'),
('VM'),
('web'),
('whiteboard'),
('Workflow Management Platform'),
('Zustand')
 ON CONFLICT ("name") DO NOTHING;