INSERT INTO "public"."Tag" ("name") VALUES
('3D'),
('agile'),
('ai'),
('AI/ML'),
('analytics'),
('angular'),
('api'),
('appliance'),
('architecture'),
('artifacts'),
('auditing'),
('availability'),
('backend'),
('behavior'),
('bi'),
('blockchain'),
('bpmn'),
('business'),
('change management'),
('CI/CD'),
('cloud'),
('cms'),
('coaching'),
('coaching individuel'),
('conduite du changement'),
('confidentiality'),
('consulting'),
('containers'),
('craftsmanship'),
('crisismanagement'),
('data'),
('database'),
('Data Engineering Pipelines'),
('delivery'),
('design'),
('design system'),
('Design Thinking'),
('desktop'),
('devops'),
('docker'),
('documentation'),
('Eco-Conception'),
('Eco-Ingénierie'),
('elastic'),
('ergonomie'),
('execution'),
('facilitation'),
(',fgg'),
('field'),
('framework'),
('frontend'),
('gaming'),
('gcp'),
('Generative AI'),
('gestion de risques'),
('gouvernance'),
('governance'),
('graph'),
('greenit'),
('hardening'),
('hardware'),
('ias'),
('ide'),
('identity'),
('influence'),
('integrity'),
('iot'),
('java'),
('javascript'),
('JAVASCRIPT'),
('kafka'),
('kubernetes'),
('language'),
('Language'),
('lean'),
('library'),
('low-code'),
('LOW LEVEL'),
('Machine Learning'),
('management'),
('Microfront end'),
('Microservice'),
('middleware'),
('ml'),
('mobile'),
('modeling'),
('monitoring'),
('network'),
('nocode'),
('nosql'),
('observability'),
('opensource'),
('organisation'),
('organization'),
('os'),
('paradigm'),
('performance'),
('php'),
('platform'),
('product'),
('programming'),
('prototyping'),
('PYSPARK'),
('python'),
('Python'),
('qa'),
('reactive programming'),
('recruitment'),
('relations'),
('Remotion'),
('repository'),
('research'),
('sales'),
('scala'),
('search'),
('security'),
('sre'),
('strategy'),
('strength'),
('testing'),
('tooling'),
('transformation'),
('typescript'),
('ux'),
('ux design'),
('virtualization'),
('web'),
('whiteboard'),
('Workflow Management Platform')
 ON CONFLICT ("name") DO NOTHING;