INSERT INTO "public"."Tag" ("name") VALUES
('3D'),
('agile'),
('ai'),
('analytics'),
('api'),
('appliance'),
('architecture'),
('artifacts'),
('auditing'),
('availability'),
('backend'),
('behavior'),
('bi'),
('blockchain'),
('business'),
('change management'),
('CI/CD'),
('cloud'),
('cms'),
('coaching'),
('coaching individuel'),
('conduite du changement'),
('confidentiality'),
('consulting'),
('containers'),
('craftsmanship'),
('crisismanagement'),
('data'),
('database'),
('delivery'),
('design'),
('Design Thinking'),
('desktop'),
('devops'),
('docker'),
('documentation'),
('Eco-Conception'),
('Eco-Ingénierie'),
('elastic'),
('ergonomie'),
('execution'),
('facilitation'),
(',fgg'),
('field'),
('framework'),
('frontend'),
('gaming'),
('gcp'),
('gestion de risques'),
('gouvernance'),
('governance'),
('graph'),
('greenit'),
('hardening'),
('ias'),
('ide'),
('identity'),
('influence'),
('integrity'),
('iot'),
('java'),
('JAVASCRIPT'),
('kafka'),
('kubernetes'),
('language'),
('lean'),
('library'),
('LOW LEVEL'),
('management'),
('Microfront end'),
('Microservice'),
('middleware'),
('ml'),
('mobile'),
('modeling'),
('monitoring'),
('network'),
('nosql'),
('organisation'),
('organization'),
('os'),
('paradigm'),
('performance'),
('php'),
('platform'),
('product'),
('programming'),
('prototyping'),
('PYSPARK'),
('python'),
('Python'),
('qa'),
('reactive programming'),
('recruitment'),
('relations'),
('Remotion'),
('repository'),
('research'),
('sales'),
('scala'),
('search'),
('security'),
('sre'),
('strategy'),
('strength'),
('testing'),
('tooling'),
('transformation'),
('typescript'),
('ux'),
('ux design'),
('virtualization'),
('web'),
('whiteboard')
 ON CONFLICT ("name") DO NOTHING;