INSERT INTO "public"."Topic" ("type", "name") VALUES
('sensitivity', 'Agile'),
('domain', 'Analytics Engineering'),
('sensitivity', 'API & Integration'),
('sensitivity', 'Architecture'),
('sensitivity', 'Artificial Intelligence'),
('domain', 'Backend (servers)'),
('generic', 'Business'),
('sensitivity', 'CI/CD & Automation'),
('sensitivity', 'Cloud'),
('sensitivity', 'Craftsmanship'),
('domain', 'Data engineering'),
('domain', 'Data Science / Analytics'),
('domain', 'Delivery'),
('sensitivity', 'Design'),
('sensitivity', 'Development process'),
('sensitivity', 'FinOps'),
('domain', 'Frontend (UI)'),
('sensitivity', 'Green'),
('domain', 'Infrastructure / Ops'),
('sensitivity', 'Management'),
('domain', 'Observability'),
('domain', 'Organization / Collaboration'),
('domain', 'Platform Engineering'),
('domain', 'Product'),
('generic', 'Professional behavior'),
('generic', 'Programming language'),
('domain', 'Quality assurance'),
('sensitivity', 'Security'),
('generic', 'Spoken language'),
('domain', 'SRE / Reliability'),
('sensitivity', 'Testing / Quality Engineering')
 ON CONFLICT ("name") DO UPDATE SET "type" = EXCLUDED."type";