INSERT INTO "Certification" ("name", "certBody", "verified") VALUES
('Advanced Certified Scrum Master', 'Scrum Alliance', true),
('Advanced Certified Scrum Product Owner', 'Scrum Alliance', true),
('Apache Cassandra 3.x Administrator Associate Certification', 'DataStax', true),
('Apache Cassandra 3.x Developer Associate Certification', 'DataStax', true),
('Associate Cloud Engineer', 'Google Cloud', true),
('Authorized Trainer', 'Google Cloud', true),
('AWS Certified Big Data - Specialty', 'AWS', true),
('AWS Certified Cloud Practitioner', 'AWS', true),
('AWS Certified Developer - Associate', 'AWS', true),
('AWS Certified DevOps Engineer - Professional', 'AWS', true),
('AWS Certified Machine Learning - Specialty', 'AWS', true),
('AWS Certified Security - Specialty', 'AWS', true),
('AWS Certified Solutions Architect - Associate', 'AWS', true),
('AWS Certified Solutions Architect - Professional', 'AWS', true),
('AWS Certified SysOps Administrator - Associate', 'AWS', true),
('BigQuery Qualified Developer', 'Google Cloud', true),
('CCA Spark and Hadoop Developer', 'Cloudera', true),
('Certificat de connaissance Numérique Responsable', 'INR', true),
('Certification "facilitation collaborative avec les Innovation Games" - RS5580', 'CréAgile', true),
('Certified CloudBees Jenkins Engineer', 'CloudBees', true),
('Certified CloudBees Jenkins Platform Engineer', 'CloudBees', true),
('Certified Kubernetes Administrator', 'CNCF', true),
('Certified Kubernetes Application Developer', 'CNCF', true),
('Certified Kubernetes Security Specialist', 'CNCF', true),
('Certified Rancher Operator: Level One', 'Rancher', true),
('Certified SAFe 4 Agilist', 'SAFe', true),
('Certified SAFe 4 Lean Portfolio Manager', 'SAFe', true),
('Certified SAFe 4 Program Consultant', 'SAFe', true),
('Certified SAFe 4 Scrum Master', 'SAFe', true),
('Certified SAFe 5 Agilist', 'SAFe', true),
('Certified SAFe 5 Lean Portfolio Manager', 'SAFe', true),
('Certified SAFe 5 Program Consultant', 'SAFe', true),
('Certified SAFe 5 Scrum Master', 'SAFe', true),
('Certified SAFe 6 Agilist', 'SAFe', true),
('Certified SAFe 6 Architect', 'SAFe', true),
('Certified SAFe 6 Lean Portfolio Manager', 'SAFe', true),
('Certified SAFe 6 Product Owner / Manager', 'SAFe', true),
('Certified SAFe 6 Scrum Master', 'SAFe', true),
('Certified Scrum Master', 'Scrum Alliance', true),
('Certified Scrum Product Owner', 'Scrum Alliance', true),
('Certified Scrum Professional Product Owner', 'Scrum Alliance', true),
('Certified Scrum Professional Scrum Master', 'Scrum Alliance', true),
('Cloud Digital Leader', 'Google Cloud', true),
('Confluent Certified Administrator for Apache Kafka', 'Confluent', true),
('Confluent Certified Developer for Apache Kafka', 'Confluent', true),
('Design Sprint', 'AJ&Smart', true),
('Docker Certified Associate', 'Mirantis', true),
('Docker Fundamentals', 'Mirantis', true),
('Eco-conception de services numériques', 'GreenIT.fr', true),
('Eco-conception de services numériques - formation accélérée', 'Zenika', true),
('EcoZ - 1/2 journée de sensibilisation', 'Zenika', true),
('Elastic Certified Analyst', 'Elastic', true),
('Elastic Certified Engineer', 'Elastic', true),
('Elastic Certified Observability Engineer', 'Elastic', true),
('FinOps Certified Practitioner', 'The Linux Foundation', true),
('GitLab Certified Associate', 'GitLab', true),
('GitLab Certified CI/CD Specialist', 'GitLab', true),
('Google Cloud Sales Credentials', 'Google Cloud', true),
('Google UX Design Professional Certificate', 'Google', true),
('Green-IT - Etat de l''art', 'GreenIT.fr', true),
('HashiCorp Certified: Consul Associate', 'Hashicorp', true),
('HashiCorp Certified: Terraform Associate', 'HashiCorp', true),
('HashiCorp Certified: Vault Associate', 'Hashicorp', true),
('HashiCorp Certified: Vault Operations Professional', 'Hashicorp', true),
('ITIL 3 Foundation', 'Axelos', true),
('ITIL 4 Foundation', 'Axelos', true),
('Java Foundation Certified Junior Associate', 'Oracle', true),
('Kubernetes Cloud Native Associate', 'CNCF', true),
('Kubernetes Cloud Native Security Associate', 'CNCF', true),
('Lean Green Belt', 'APMG International', true),
('Maîtrise de la qualité en projet Web', 'Opquast', true),
('Management 3.0', 'Management 3.0', true),
('Microsoft AZ-900: Azure Fundamentals', 'Microsoft', true),
('Microsoft Certified: Azure Administrator Associate', 'Microsoft', true),
('Microsoft Certified: Azure Data Scientist Associate', 'Microsoft', true),
('Microsoft Certified Solutions Associate: Cloud', 'Microsoft', true),
('MongoDB Certified DBA', 'MongoDB', true),
('MongoDB Certified Developer', 'MongoDB', true),
('Node.js Application Developer', 'OpenJS', true),
('Node.js Services Developer', 'OpenJS', true),
('Offensive Security Certified Professional', 'Offensive Security', true),
('PMI Agile Certified Practitioner', 'Project Management Institute', true),
('Prince2 Foundation', 'Axelos', true),
('Professional Cloud Architect', 'Google Cloud', true),
('Professional Cloud Database Engineer', 'Google Cloud', true),
('Professional Cloud Developer', 'Google Cloud', true),
('Professional Cloud Devops Engineer', 'Google Cloud', true),
('Professional Cloud Network Engineer', 'Google Cloud', true),
('Professional Cloud Security Engineer', 'Google Cloud', true),
('Professional Data Engineer', 'Google Cloud', true),
('Professional ML Engineer', 'Google Cloud', true),
('Professional Scrum Developer 1', 'scrum.org', true),
('Professional Scrum Master 1', 'scrum.org', true),
('Professional Scrum Master 2', 'scrum.org', true),
('Professional Scrum Master 3', 'scrum.org', true),
('Professional Scrum Product Owner 1', 'scrum.org', true),
('Professional Scrum Product Owner 2', 'scrum.org', true),
('Professional Scrum Product Owner 3', 'scrum.org', true),
('Professionel Scrum Certifié - RS2396', 'Kagilum', true),
('Spring Certified Professional', 'VMware', true),
('Spring Core Developer 4.3', 'Spring', true),
('Spring Core Developer 5', 'Spring', true),
('Spring Professional Certification', 'Spring', true),
('TensorFlow Developer', 'TensorFlow', true),
('TOGAF 9 Certified', 'The Open Group', true),
('TOGAF 9 Foundation', 'The Open Group', true)
 ON CONFLICT DO NOTHING;
