INSERT INTO "Certification" ("name", "certBody", "verified") VALUES
('Advanced Certified Scrum Master', 'Scrum Alliance', true),
('Advanced Certified Scrum Product Owner', 'Scrum Alliance', true),
('Apache Cassandra 3.x Administrator Associate Certification', 'DataStax', true),
('Apache Cassandra 3.x Developer Associate Certification', 'DataStax', true),
('ArchiMate 3 Foundation', 'The Open Group', true),
('ArchiMate 3 Practitioner', 'The Open Group', true),
('Associate Cloud Engineer', 'Google Cloud', true),
('Associate Data Practitioner', 'Google Cloud', true),
('Astronomer Certification for Apache Airflow Fundamentals', 'Astronomer', true),
('Astronomer Certification in Apache Airflow DAG Authoring', 'Astronomer', true),
('Authorized Trainer', 'Google Cloud', true),
('AWS Certified AI Practitioner', 'Amazon Web Services', true),
('AWS Certified Big Data - Specialty', 'AWS', true),
('AWS Certified Cloud Practitioner', 'AWS', true),
('AWS Certified Data Engineer - Associate', 'Amazon Web Services', true),
('AWS Certified Developer - Associate', 'AWS', true),
('AWS Certified DevOps Engineer - Professional', 'AWS', true),
('AWS Certified Machine Learning Engineer - Associate', 'Amazon Web Services', true),
('AWS Certified Machine Learning - Specialty', 'AWS', true),
('AWS Certified Security - Specialty', 'AWS', true),
('AWS Certified Solutions Architect - Associate', 'AWS', true),
('AWS Certified Solutions Architect - Professional', 'AWS', true),
('AWS Certified SysOps Administrator - Associate', 'AWS', true),
('BigQuery Qualified Developer', 'Google Cloud', true),
('CCA Spark and Hadoop Developer', 'Cloudera', true),
('CDMP Associate', 'DAMA International', true),
('CDMP Master', 'DAMA International', true),
('CDMP Practitioner', 'DAMA International', true),
('Certificat de connaissance Numérique Responsable', 'INR', true),
('Certification "facilitation collaborative avec les Innovation Games" - RS5580', 'CréAgile', true),
('Certified CloudBees Jenkins Engineer', 'CloudBees', true),
('Certified CloudBees Jenkins Platform Engineer', 'CloudBees', true),
('Certified Kubernetes Administrator', 'CNCF', true),
('Certified Kubernetes Application Developer', 'CNCF', true),
('Certified Kubernetes Security Specialist', 'CNCF', true),
('Certified Rancher Operator: Level One', 'Rancher', true),
('Certified SAFe 4 Agilist', 'SAFe', true),
('Certified SAFe 4 Lean Portfolio Manager', 'SAFe', true),
('Certified SAFe 4 Program Consultant', 'SAFe', true),
('Certified SAFe 4 Scrum Master', 'SAFe', true),
('Certified SAFe 5 Agilist', 'SAFe', true),
('Certified SAFe 5 Lean Portfolio Manager', 'SAFe', true),
('Certified SAFe 5 Program Consultant', 'SAFe', true),
('Certified SAFe 5 Scrum Master', 'SAFe', true),
('Certified SAFe 6 Agilist', 'SAFe', true),
('Certified SAFe 6 Architect', 'SAFe', true),
('Certified SAFe 6 Lean Portfolio Manager', 'SAFe', true),
('Certified SAFe 6 Product Owner / Manager', 'SAFe', true),
('Certified SAFe 6 Scrum Master', 'SAFe', true),
('Certified Scrum Master', 'Scrum Alliance', true),
('Certified Scrum Product Owner', 'Scrum Alliance', true),
('Certified Scrum Professional Product Owner', 'Scrum Alliance', true),
('Certified Scrum Professional Scrum Master', 'Scrum Alliance', true),
('Certified Senior Vue.js Developer', 'Certificates.dev', true),
('Certified Vue.js Developer', 'Certificates.dev', true),
('Clever Cloud Certified - Advanced Deployments', 'Clever Cloud', true),
('Clever Cloud Certified - Cloud Concepts 101', 'Clever Cloud', true),
('Cloud Digital Leader', 'Google Cloud', true),
('Confluent Certified Administrator for Apache Kafka', 'Confluent', true),
('Confluent Certified Developer for Apache Kafka', 'Confluent', true),
('Databricks Certified Data Analyst Associate', 'Databricks', true),
('Databricks Certified Data Engineer Associate', 'Databricks', true),
('Databricks Certified Data Engineer Professional', 'Databricks', true),
('Databricks Certified Generative AI Engineer Associate', 'Databricks', true),
('Databricks Certified Machine Learning Associate', 'Databricks', true),
('Databricks Certified Machine Learning Professional', 'Databricks', true),
('Data Vault 2.0 Certified Practitioner', 'Data Vault Alliance', true),
('dbt Certified Architect', 'dbt Labs', true),
('dbt Certified Developer', 'dbt Labs', true),
('Design Sprint', 'AJ&Smart', true),
('DevOps Foundation Certification', 'DevOps Foundation', true),
('Docker Certified Associate', 'Mirantis', true),
('Docker Fundamentals', 'Mirantis', true),
('Eco-conception de services numériques', 'GreenIT.fr', true),
('Eco-conception de services numériques - formation accélérée', 'Zenika', true),
('EcoZ - 1/2 journée de sensibilisation', 'Zenika', true),
('Elastic Certified Analyst', 'Elastic', true),
('Elastic Certified Engineer', 'Elastic', true),
('Elastic Certified Observability Engineer', 'Elastic', true),
('FinOps Certified Practitioner', 'The Linux Foundation', true),
('Generative AI Leader', 'Google Cloud', true),
('GitLab Certified Agile Portfolio Management Associate', 'GitLab', true),
('GitLab Certified Associate', 'GitLab', true),
('GitLab Certified CI/CD Associate', 'GitLab', true),
('GitLab Certified CI/CD Specialist', 'GitLab', true),
('GitLab Certified Duo Agent Platform Associate', 'GitLab', true),
('GitLab Certified Implementation Services', 'GitLab', true),
('GitLab Certified Migration Services Certification', 'GitLab', true),
('GitLab Certified Security Associate', 'GitLab', true),
('GitLab Fundamentals Associate', 'GitLab', true),
('GitLab Solution Architect Core Verified Associate', 'GitLab', true),
('Google Cloud Sales Credentials', 'Google Cloud', true),
('Google UX Design Professional Certificate', 'Google', true),
('Green-IT - Etat de l''art', 'GreenIT.fr', true),
('Green Software for Practitioners (LFC131)', 'Linux Foundation', true),
('HashiCorp Certified: Consul Associate', 'Hashicorp', true),
('HashiCorp Certified: Terraform Associate', 'HashiCorp', true),
('HashiCorp Certified: Vault Associate', 'Hashicorp', true),
('HashiCorp Certified: Vault Operations Professional', 'Hashicorp', true),
('ITIL 3 Foundation', 'Axelos', true),
('ITIL 4 Foundation', 'Axelos', true),
('Java Foundation Certified Junior Associate', 'Oracle', true),
('Kanban Management Professional (KMP)', 'Kanban University', true),
('Kanban System Design (KSD)', 'Kanban University', true),
('Kong Gateway Certified Associate', 'Kong', true),
('Kubernetes Cloud Native Associate', 'CNCF', true),
('Kubernetes Cloud Native Security Associate', 'CNCF', true),
('Lean Green Belt', 'APMG International', true),
('LILATE English B1', 'Lingueo', true),
('LILATE English B2', 'Lingueo', true),
('LILATE English C1', 'Lingueo', true),
('LILATE English C2', 'Lingueo', true),
('Maîtrise de la qualité en projet Web', 'Opquast', true),
('Management 3.0', 'Management 3.0', true),
('Master Figma Course: From Beginner to Figma Pro', 'SaaS Design', true),
('Microsoft AZ-900: Azure Fundamentals', 'Microsoft', true),
('Microsoft Certified: Azure Administrator Associate', 'Microsoft', true),
('Microsoft Certified: Azure AI Engineer Associate (AI-102)', 'Microsoft', true),
('Microsoft Certified: Azure AI Fundamentals (AI-900)', 'Microsoft', true),
('Microsoft Certified: Azure Data Engineer Associate (DP-203)', 'Microsoft', true),
('Microsoft Certified: Azure Data Scientist Associate', 'Microsoft', true),
('Microsoft Certified: Azure Developer Associate (AZ-204)', 'Microsoft', true),
('Microsoft Certified: Azure DevOps Engineer Expert (AZ-400)', 'Microsoft', true),
('Microsoft Certified: Azure Solutions Architect Expert (AZ-305)', 'Microsoft', true),
('Microsoft Certified: Fabric Data Engineer Associate (DP-700)', 'Microsoft', true),
('Microsoft Certified Solutions Associate: Cloud', 'Microsoft', true),
('Mid-Level Vue.js Developer', 'certificates.dev', true),
('MongoDB Certified DBA', 'MongoDB', true),
('MongoDB Certified Developer', 'MongoDB', true),
('Node.js Application Developer', 'OpenJS', true),
('Node.js Services Developer', 'OpenJS', true),
('NVIDIA-Certified Associate: Generative AI and LLMs (NCA-GENL)', 'NVIDIA', true),
('Offensive Security Certified Professional', 'Offensive Security', true),
('Open Agile Architecture Foundation', 'The Open Group', true),
('Oracle Certified Associate Java SE 8 Programmer', 'Oracle', true),
('Oracle Certified Professional Java SE 11 Developer', 'Oracle', true),
('Oracle Certified Professional Java SE 21 Developer', 'Oracle', true),
('OVHcloud Certified Sales / Presales - Discover', 'OVHcloud', true),
('OVHcloud Certified Solution Architect - Discover', 'OVHcloud', true),
('OVHcloud Certified Support / Technical Account Manager - Discover', 'OVHcloud', true),
('PMI Agile Certified Practitioner', 'Project Management Institute', true),
('Prince2 Foundation', 'Axelos', true),
('Professional Agentic Architect', 'Google Cloud', true),
('Professional Cloud Architect', 'Google Cloud', true),
('Professional Cloud Database Engineer', 'Google Cloud', true),
('Professional Cloud Developer', 'Google Cloud', true),
('Professional Cloud Devops Engineer', 'Google Cloud', true),
('Professional Cloud Network Engineer', 'Google Cloud', true),
('Professional Cloud Security Engineer', 'Google Cloud', true),
('Professional Data Engineer', 'Google Cloud', true),
('Professional ML Engineer', 'Google Cloud', true),
('Professional Scrum Developer 1', 'scrum.org', true),
('Professional Scrum Master 1', 'scrum.org', true),
('Professional Scrum Master 2', 'scrum.org', true),
('Professional Scrum Master 3', 'scrum.org', true),
('Professional Scrum Product Owner 1', 'scrum.org', true),
('Professional Scrum Product Owner 2', 'scrum.org', true),
('Professional Scrum Product Owner 3', 'scrum.org', true),
('Professionnel Scrum Certifié - RS2396', 'Kagilum', true),
('R2Devops Certified Partner Consultant', 'R2Devops', true),
('Red Hat Certified Architect (RHCA)', 'Red Hat', true),
('Red Hat Certified Engineer (RHCE)', 'Red Hat', true),
('Red Hat Certified Instructor (RHCI)', 'Red Hat', true),
('Red Hat Certified OpenShift Administrator DO180', 'Red Hat', true),
('Red Hat Certified OpenShift Administrator DO280', 'Red Hat', true),
('Red Hat Certified Specialist in Building Resilient Microservices EX328', 'Red Hat', true),
('Red Hat Certified Specialist in Containers EX188', 'Red Hat', true),
('Red Hat Certified Specialist in Developing Automation with AAP', 'Red Hat', true),
('Red Hat Certified Specialist in Managing Automation with AAP EX467', 'Red Hat', true),
('Red Hat Certified System Administrator (RHCSA)', 'Red Hat', true),
('Scaleway Professional Solution Architect', 'Scaleway', true),
('Senior Vue.js Developer', 'certificates.dev', true),
('SnowPro Advanced: Architect', 'Snowflake', true),
('SnowPro Advanced: Data Analyst', 'Snowflake', true),
('SnowPro Advanced: Data Engineer', 'Snowflake', true),
('SnowPro Advanced: Data Scientist', 'Snowflake', true),
('SnowPro Core Certification', 'Snowflake', true),
('Spring Certified Professional', 'VMware', true),
('Spring Core Developer 4.3', 'Spring', true),
('Spring Core Developer 5', 'Spring', true),
('Spring Professional Certification', 'Spring', true),
('TensorFlow Developer', 'TensorFlow', true),
('The Complete Design System Course for Figma (Advanced)', 'SaaS Design', true),
('The Complete Figma Design System Course (Advanced)', 'SaaS Design', true),
('The Open Group Certified Architect (Open CA)', 'The Open Group', true),
('TOGAF 9 Certified', 'The Open Group', true),
('TOGAF 9 Foundation', 'The Open Group', true),
('TOGAF Enterprise Architecture Foundation', 'The Open Group', true),
('TOGAF Enterprise Architecture Practitioner', 'The Open Group', true)
 ON CONFLICT DO NOTHING;