version: 2.1

orbs:
  cypress: cypress-io/cypress@1

executors:
  node:
    docker:
      - image: circleci/node:16.13.0
  hasura:
    docker:
      - image: cimg/node:16.13.0
      # - image: postgres:12
      #   name: postgres
      #   environment:
      #     POSTGRES_USER: postgres
      #     POSTGRES_DB: postgres
      #     PGPORT: 5432
      # - image: hasura/graphql-engine:v2.0.6.cli-migrations-v3
      #   name: hasura
      #   environment:
      #     HASURA_GRAPHQL_DATABASE_URL: postgresql://postgres:@localhost:5432/postgres
      #     HASURA_GRAPHQL_ADMIN_SECRET: key
  docker:
    docker:
      - image: docker:stable

jobs:
  install-dependencies:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-packaging-dependencies-{{ checksum "package-lock.json" }}
            - v4-packaging-dependencies-
      - run:
          name: install-dependencies
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v4-packaging-dependencies-{{ checksum "package-lock.json" }}
  qc-prettier:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-packaging-dependencies-{{ checksum "package-lock.json" }}
            - v4-packaging-dependencies-
      - run:
          name: qc-prettier
          command: npm run prettier:check
  hasura-test-apply-migrations:
    executor: hasura
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v4-packaging-dependencies-{{ checksum "package-lock.json" }}
            - v4-packaging-dependencies-
      - run:
          name: "Create env.local file"
          command: echo -e "NEXT_PUBLIC_GRAPHQL_URL=http://localhost:8080/v1/graphql\nNEXT_PUBLIC_BASE_URL=http://localhost:3000\nHASURA_ADMIN_SECRET=key\nNEXT_API_BEARER_TOKEN=Bearer key\nHASURA_ACHIEVEMENTS_ENDPOINT=http://172.17.0.1:3000/api/achievement" >> .env.local
      - run:
          name: "docker-compose up -d"
          command: docker-compose up -d
      - run:
          name: "install hasura cli"
          command: sudo npm i -g hasura-cli
      - run:
          name: "wait for Hasura for a minute max"
          command: dockerize -wait tcp://localhost:8080 -timeout 1m
      - run:
          name: migrate
          working_directory: hasura
          command: hasura migrate apply --endpoint http://localhost:8080
      - run:
          name: metadata
          working_directory: hasura
          command: hasura metadata apply --endpoint http://localhost:8080
      - run:
          name: generate types
          command: NEXT_PUBLIC_GRAPHQL_URL=http://localhost:8080 HASURA_ADMIN_SECRET=key npm run generate
      - save_cache:
          paths:
            - ./src/generated
          key: v4-packaging-types-{{ $CIRCLE_SHA1 }}
  build:
    executor: node
    parameters:
      graphql-url:
        type: string
      base-url:
        type: string
      admin-secret:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-packaging-dependencies-{{ checksum "package-lock.json" }}
            - v4-packaging-dependencies-
      - run:
          name: build
          command: NEXT_PUBLIC_BASE_URL=<< parameters.base-url >> NEXT_PUBLIC_GRAPHQL_URL=<< parameters.graphql-url >> npm run build
  unit-test:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-packaging-dependencies-{{ checksum "package-lock.json" }}
            - v4-packaging-dependencies-
            - v4-packaging-types-{{ $CIRCLE_SHA1 }}
      - run:
          name: unit-test
          command: npm run test:unit
  deploy-hasura:
    parameters:
      hasura-deploy-dir:
        type: string
        default: ../hasura
      hasura-clever-app-id:
        type: string
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Package Hasura
          command: |
            mkdir --parents << parameters.hasura-deploy-dir >>
            cp ./hasura.Dockerfile << parameters.hasura-deploy-dir >>/Dockerfile
      - run:
          name: Deploy Hasura
          working_directory: << parameters.hasura-deploy-dir >>
          command: |
            git config --global user.email "dsi@zenika.com"
            git config --global user.name "Zenika"
            git init
            git add .
            git commit -m "deploy!"
            sudo npm install --global clever-tools
            clever login --secret=$CLEVER_SECRET --token=$CLEVER_TOKEN
            clever link << parameters.hasura-clever-app-id >>
            clever deploy --force
  run-migrations:
    docker:
      - image: hasura/graphql-engine:v1.3.2.cli-migrations-v2
    parameters:
      hasura-admin-secret:
        type: string
      hasura-endpoint:
        type: string
    steps:
      - checkout
      - run:
          name: Apply migrations
          working_directory: hasura
          command: hasura-cli migrate apply --admin-secret << parameters.hasura-admin-secret >> --endpoint << parameters.hasura-endpoint >>
      - run:
          name: Apply metadata
          working_directory: hasura
          command: hasura-cli metadata apply --admin-secret << parameters.hasura-admin-secret >> --endpoint << parameters.hasura-endpoint >>
  deploy:
    executor: node
    parameters:
      graphql-url:
        type: string
      clever-app-id:
        type: string
      base-url:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-packaging-dependencies-{{ checksum "package-lock.json" }}
            - v4-packaging-dependencies-
      - run:
          name: build
          command: NEXT_PUBLIC_BASE_URL=<< parameters.base-url >> NEXT_PUBLIC_GRAPHQL_URL=<< parameters.graphql-url >> npm run build
      - run:
          name: Package
          command: |
            mkdir deploy
            cp -r .next deploy
            cp -r public deploy
            cp package.json deploy
            cp package-lock.json deploy
            cp next.config.js deploy
      - run:
          name: Deploy
          working_directory: deploy
          command: |
            git config --global user.email "dsi@zenika.com"
            git config --global user.name "Zenika"
            git init
            git add .
            git commit -m "deploy!"
            sudo npm install --global clever-tools
            clever login --secret=$CLEVER_SECRET --token=$CLEVER_TOKEN
            clever link << parameters.clever-app-id >>
            clever deploy --force

workflows:
  qc-test-deploy-staging:
    jobs:
      - install-dependencies
      - hasura-test-apply-migrations:
          requires:
            - install-dependencies
      - qc-prettier:
          requires:
            - install-dependencies
      - unit-test:
          requires:
            - install-dependencies
      # - cypress/install:
      #     cache-key: >-
      #       v4-packaging-dependencies-cypress-{{ checksum "package-lock.json" }}
      # - cypress/run:
      #     name: chrome-cypress-run
      #     requires:
      #       - cypress/install
      #     cache-key: >-
      #       v4-packaging-dependencies-cypress-{{ checksum "package-lock.json" }}
      #     start: npm run dev
      #     wait-on: "http://localhost:3000"
      #     executor: cypress/browsers-chrome78-ff70
      #     browser: chrome
      #     parallel: true
      #     parallelism: 2
      # - cypress/run:
      #     name: firefox-cypress-run
      #     requires:
      #       - cypress/install
      #     cache-key: >-
      #       v4-packaging-dependencies-cypress-{{ checksum "package-lock.json" }}
      #     start: npm run dev
      #     wait-on: "http://localhost:3000"
      #     executor: cypress/browsers-chrome78-ff70
      #     browser: firefox
      #     parallel: true
      #     parallelism: 2
      - build:
          name: build-staging
          requires:
            - qc-prettier
            - unit-test
            - hasura-test-apply-migrations
          graphql-url: $NEXT_STAGING_PUBLIC_GRAPHQL_URL
          admin-secret: $HASURA_ADMIN_SECRET_STAGING
          base-url: $NEXT_STAGING_BASE_URL
      - deploy-hasura:
          name: deploy-hasura-staging
          hasura-clever-app-id: app_dd676b9a-5e95-4bab-9e21-ba6f9582e12b
          requires:
            - build-staging
            # - hasura-test-apply-migrations
          context: clever-cloud2-zenika-dev
          filters: &deploy-staging-filters
            branches:
              only: main
      - run-migrations:
          name: run-migrations-staging
          hasura-admin-secret: $HASURA_ADMIN_SECRET_STAGING
          hasura-endpoint: $HASURA_ENDPOINT_STAGING
          requires:
            - deploy-hasura-staging
          filters: *deploy-staging-filters
      - deploy:
          name: deploy-staging
          requires:
            - run-migrations-staging
          graphql-url: $NEXT_STAGING_PUBLIC_GRAPHQL_URL
          base-url: $NEXT_STAGING_BASE_URL
          clever-app-id: app_ca84588b-5a62-4b57-a5f0-86260c6382a5
          context: clever-cloud2-zenika-dev
          filters: *deploy-staging-filters

  qc-test-deploy:
    jobs:
      - install-dependencies:
          filters: &deploy-filters
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - hasura-test-apply-migrations:
          requires:
            - install-dependencies
      - qc-prettier:
          requires:
            - install-dependencies
          filters: *deploy-filters
      - unit-test:
          requires:
            - install-dependencies
          filters: *deploy-filters
      - build:
          name: build
          requires:
            - qc-prettier
            - unit-test
            - hasura-test-apply-migrations
          graphql-url: $NEXT_PROD_PUBLIC_GRAPHQL_URL
          admin-secret: $HASURA_ADMIN_SECRET_STAGING
          base-url: $NEXT_PROD_BASE_URL
          filters: *deploy-filters
      - deploy-hasura:
          name: deploy-hasura
          hasura-clever-app-id: $HASURA_CLEVER_APP_ID_PROD
          requires:
            - build
          context: clever-cloud2-zenika-dev
          filters: *deploy-filters
      - run-migrations:
          name: run-migrations
          hasura-admin-secret: $HASURA_ADMIN_SECRET_PROD
          hasura-endpoint: $HASURA_ENDPOINT_PROD
          requires:
            - deploy-hasura
          filters: *deploy-filters
      - deploy:
          name: deploy
          requires:
            - run-migrations
          graphql-url: $NEXT_PROD_PUBLIC_GRAPHQL_URL
          base-url: $NEXT_PROD_BASE_URL
          clever-app-id: $CLEVER_APP_ID_PROD
          context: clever-cloud2-zenika-dev
          filters: *deploy-filters
