apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: zenika/zprofile-front
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  selector:
    app: front
  ports:
    - port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: front-ingress-route
spec:
  routes:
    - kind: Rule
      priority: 1
      match: PathPrefix("/")
      services:
        - kind: Service
          name: front
          port: 80
