name: Update Skills referential

#on:
#  schedule:
#    # At 17:00 on Friday
#    - cron: '0 17 * * 5'
on:
  push:
    # only trigger on branches, not on tags
    branches: 'chore/automated_skill_pr'

jobs:
  update-referential:
    name: Update Skills referential
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: chore/skills_referential
          fetch-depth: 0

      - name: Update referential
        run: |
          date > generated.txt

      - name: Commit
        run: |
          git add .
          git commit -m "generated"
          git push

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: '🌱 Update Skills referential',
              owner,
              repo,
              head: '${{ github.ref_name }}',
              base: 'main',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['automated pr']
            });
