-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."UserNotifications" add column "notification_id" integer
--  not null;
